# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      # Test the cmake versions available on ubuntu lts releases as well as other important versions
      # like the minimum required and the latest available and major version changes to have a
      # decent coverage of cmake versions.
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        cmake_version: ['3.19.7', # minimum required for cmake json support
                        '3.22.1', # 22.04 LTS
                        '3.28.3', # 24.04 LTS
                        '3.31.10', # last 3.x
                        '4.2.1']
        exclude:
          - os: windows-latest
            cmake_version: '3.19.7' # there seems to be a bug with compiler detection

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: ${{ matrix.cmake_version }}

    - name: Print CMake version
      run: cmake --version

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}
      env:
        CMAKE_VERSION: ${{ matrix.cmake_version }}

    - name: Install
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --target install
      env:
        CMAKE_VERSION: ${{ matrix.cmake_version }}

    - name: Run Tests
      run: >
        cd ${{ steps.strings.outputs.build-output-dir }} &&
        ctest . --output-on-failure